name: 'Custom Github Action'
description: 'takes number and return the squared number'
input: 
  num:
  required:
  default: "1"
outputs:
  num_squared:
    value: ${{}}
  runs:
    using: 'composite'
    steps: 
     - name: Install python
       uses: action/setup-python@v4
       with:
    python-version: '3.10'
    -name: Install dependencies
    run: pip install -r requirements.txt
    shell: bash
    -name: Pass inputs to shell
    run: |
    echo "INPUT_NUM=${{ inputs.num }}" >> $GITHUB_ENV
    shell: bash
    -name: Fetch the num
    
  
